import "./globals.css";
import NavbarServer from "@/app/components/navbarServer";
import Footer from "@/app/components/Footer";

export const metadata = {
  title: "Subha Cyber Solutions",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Subha Cyber Solutions</title>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className="min-h-screen flex flex-col bg-gray-800 text-white font-sans">
        <header>
          <NavbarServer />
        </header>
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
